### ISSUE TITLE
DearEIS bug report DRT analysis

### ISSUE THREAD

**Issue by andremugen24** [vyrjana/DearEIS#13]
Traceback (most recent call last):
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\pyimpspec\analysis\drt\tr_rbf.py", line 1437, in _attempt_importing_solver
    import cvxpy
ModuleNotFoundError: No module named 'cvxpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\pyimpspec\analysis\drt\tr_rbf.py", line 1440, in _attempt_importing_solver
    import kvxopt
ModuleNotFoundError: No module named 'kvxopt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\pyimpspec\analysis\drt\tr_rbf.py", line 1602, in calculate_drt_tr_rbf
    _attempt_importing_solver()
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\pyimpspec\analysis\drt\tr_rbf.py", line 1442, in _attempt_importing_solver
    import cvxopt
ModuleNotFoundError: No module named 'cvxopt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\deareis\signals.py", line 179, in emit
    func(*args, **kwargs)
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\deareis\program\drt.py", line 107, in perform_drt
    drt: DRTResult = api.calculate_drt(
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\deareis\api\drt.py", line 76, in calculate_drt
    result: _pyimpspec.DRTResult = _pyimpspec.calculate_drt(
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\pyimpspec\analysis\drt\__init__.py", line 91, in calculate_drt
    return {
  File "C:\Users\anruss\AppData\Roaming\Python\Python310\site-packages\pyimpspec\analysis\drt\tr_rbf.py", line 1604, in calculate_drt_tr_rbf
    raise DRTError("Failed to import any of the supported convex optimizers!")
pyimpspec.exceptions.DRTError: Failed to import any of the supported convex optimizers!

**Comment by vyrjana** [comment]
Hi!

The TR-RBF method requires that **at least one** of the following convex optimization packages has been installed:
- [cvxpy](https://pypi.org/project/cvxpy/)
- [cvxopt](https://pypi.org/project/cvxopt/)
- [kvxopt](https://pypi.org/project/kvxopt/)

If you installed DearEIS using pipx, then you should be able to install the missing package(s) by using the `inject` command (see the [example provided here in pipx's documentation](https://pypa.github.io/pipx/examples/)).

**Comment by andremugen24** [comment]
Thank you very much :)
