### ISSUE TITLE
AssertionError after updating to 5.0.0

### ISSUE THREAD

**Issue by Up2nothing** [vyrjana/DearEIS#19]
**Desktop (please complete the following information):**
- _DearEIS_ version 5.0.0
- Python version3.11.9
- OS: Windows 10

**Describe the bug**
Error on start up.
`AssertionError: (<KramersKronigTest.REAL_LEASTSQ: 7>, 7, 'test')`

**To Reproduce**
1. Update to Dear EIS 5.0.0
2. Run DearEIS

**Expected behavior**
Start up with no errors.

**Screenshots/videos/tracebacks**
If applicable, add screenshots/videos/tracebacks to help explain your problem.

Hier is my inputs and outputs from the consol:

Successfully installed deareis-5.0.0
PS C:\Users\oswaldki\Desktop\EIS Auswertung - Python Code> pip show deareis
WARNING: Ignoring invalid distribution ~eareis (C:\Users\oswaldki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages)
Name: deareis
Version: 5.0.0
Summary: A GUI program for analyzing, simulating, and visualizing impedance spectra.
Home-page: https://vyrjana.github.io/DearEIS
Author: DearEIS developers
Author-email:
License: GPLv3
Location: C:\Users\oswaldki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
Requires: dearpygui, pyimpspec, requests
Required-by:
PS C:\Users\oswaldki\Desktop\EIS Auswertung - Python Code> python -m deareis

Traceback (most recent call last):
  File "C:\Users\oswaldki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deareis\config\__init__.py", line 250, in __init__
    self.load()
  File "C:\Users\oswaldki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deareis\config\__init__.py", line 500, in load
    dictionary = self.merge_dicts(dictionary, self.to_dict())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oswaldki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deareis\config\__init__.py", line 467, in merge_dicts
    self.check_type(value, default[key], key)
  File "C:\Users\oswaldki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deareis\config\__init__.py", line 451, in check_type
    self.check_type(user[key], default[key], key)
  File "C:\Users\oswaldki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deareis\config\__init__.py", line 442, in check_type
    assert type(user) == type(default), (user, default, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: (<KramersKronigTest.REAL_LEASTSQ: 7>, 7, 'test')

**Comment by vyrjana** [comment]
I just published version 5.0.1, which should fix this bug for anybody else who is about to update from version 4.x or earlier. Based on my testing, anybody who runs into this issue with version 5.0.0 should only see it once since the user configuration file ends up being updated/replaced.

**Comment by Up2nothing** [comment]
Hi, wow that was a quick fix! I had a suspission  that it was a one time error, but wanted to let you know regardless.
Many thanks!

**Comment by vyrjana** [comment]
No problem and thanks for letting me know. My manual testing during development ended up missing this issue. I'll have to write some tests for migrating user configurations from the older versions to the latest version so that this kind of bug can hopefully be avoided in the future.

**Comment by vyrjana** [comment]
The next version of DearEIS will include tests for migrating old config version and some changes have been made to the source code (e.g., the Config class) to facilitate this kind of testing.
